
sudo: required
language: java

jdk:
  - openjdk8

script:
  - mvn clean compile package assembly:single -DskipTests

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/semantic-conflicts/jackson-databind/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-051bd5e447fbc9539e12a4fe90eb989dba0c656e
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true 
            